import type { Metadata } from "next";
import { Archivo_Black, Instrument_Serif, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import Header from "../components/Header";
import { cn } from "@/lib/utils";

const archivoBlack = Archivo_Black({
  variable: "--font-display",
  subsets: ["latin"],
  weight: "400", // Archivo Black yagona og'irlikda keladi
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-accent",
  subsets: ["latin"],
  weight: "400",
  style: ["italic", "normal"],
});

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", archivoBlack.variable, instrumentSerif.variable, "font-mono", jetbrainsMono.variable)}
    >
      <body className="min-h-full flex flex-col bg-paper">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}